name: watch_hub_ep
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.9
  firebase_core: ^3.14.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  provider: ^6.1.5
  marqueer: ^2.0.1
  marquee: ^2.3.0
  video_player: ^2.10.0
  flutter_svg: ^2.2.0
  firebase_auth: ^5.6.1
  google_sign_in: ^6.2.1
  foundation: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_logo.png
    - assets/images/splash_full.png

flutter_native_splash:
  color: "#0D0D0D"
  image: assets/images/splash_logo.png
  fullscreen: true

  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#0D0D0D"
    color: "#0D0D0D"

